# Generated by Django 5.1.7 on 2025-03-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_user_id_cart_user_rename_user_id_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1star', '1'), ('2star', '2'), ('3star', '3'), ('4star', '4'), ('5star', '5')], max_length=64),
        ),
    ]
